### ISSUE TITLE
RTCM corrections are not being applied using ROS2 driver and NTRIP Client

### ISSUE THREAD

**Issue by adrigmz00** [xsenssupport/Xsens_MTi_ROS_Driver_and_Ntrip_Client#20]
Hi. I'm trying to use the MTi-680 Developmet Kit with the RTK GNSS daughter card installed in on the GNSS extension socket in order to receive RTCM corrections.
I'm using the ROS2 driver (on ROS2 Humble on my NVIDIA Jetson Orin AGX) and the NTRIP client provided in this repository with my credentials of the Ublox PointPerfect Service. I have configured the MTi-680 DK as specified in this repo using the MT Manager (installed on my Windows Laptop) and when I introduce my credentials in the MT Manager and check the RTK status on it, I can verify that the DK can reach float and fix status. Moreover, the RTK led on the RTK GNSS daughter card is turned on. I attach a photo showing this:
<img width="941" alt="Image" src="https://github.com/user-attachments/assets/dd83d69a-2f6e-412b-a104-d2d9782195d1" />

On the contrary, when I use the ROS2 driver and the NTRIP client with the same credentials I check that the /rtcm topic is being publish (this means that I'm receiving corrections) but I think that maybe they are not being correctly sent to the RTK GNSS daughter card. Here are the logs I receive when I launch the MTi node:
<img width="528" alt="Image" src="https://github.com/user-attachments/assets/e26bbe94-1d3f-4842-9513-507571c5ecb7" />

And the logs I receive when launching the ntrip client:
<img width="513" alt="Image" src="https://github.com/user-attachments/assets/bd80caeb-caba-4c94-8971-2b13468f513b" />

The /nmea topic is being published:
<img width="514" alt="Image" src="https://github.com/user-attachments/assets/103c4756-0de1-47a9-895e-ceb6c5fface5" />

And the same for the /rtcm topic. An example of a message that is being published is:
```
header:
  stamp:
    sec: 1744371018
    nanosec: 728877648
  frame_id: odom
data:
- 211
- 0
- 145
- 68
- 99
- 225
- 112
- 224
- 61
- 130
- 0
- 36
- 128
- 5
- 5
- 48
- 0
- 0
- 0
- 0
- 32
- 1
- 1
- 0
- 127
- 255
- 233
- 170
- 201
- 202
- 234
- 138
- 126
- 164
- 111
- 50
- 195
- 215
- 199
- 50
- 121
- 176
- 252
- 89
- 254
- 3
- 183
- 71
- 220
- 15
- 233
- 144
- 131
- 34
- 216
- 70
- 243
- 167
- 255
- 102
- 30
- 212
- 228
- 57
- 9
- 35
- 18
- 174
- 237
- 197
- 225
- 111
- 197
- 216
- 117
- 57
- 65
- 177
- 222
- 2
- 26
- 88
- 18
- 171
- 240
- 147
- 203
- 130
- 128
- 20
- 129
- 115
- 241
- 252
- 182
- 71
- 242
- 194
- 29
- 207
- 183
- 254
- 94
- 61
- 249
- 117
- 192
- 151
- 246
- 163
- 9
- 19
- 12
- 52
- 45
- 233
- 86
- 0
- 95
- 101
- 97
- 128
- 73
- 127
- 255
- 255
- 255
- 255
- '...'
```

I have been investigating and this RTCM message corresponds to RTCM 1094 type. According to the Ublox ZED-F9P documentation on https://content.u-blox.com/sites/default/files/ZED-F9P-04B_DataSheet_UBX-21044850.pdf (pages 7 and 8) this is a message from GNSS Galileo System and it should be supported by the module.
Regarding this, when I check the /status topic, the fix status is 0, which means that it has not reached nor float nor fix. Moreover, the GGA messages shows that fix quality is 1 (the number shown after the "W"), which means that the position is not using corrections:
```
$GPGGA,073026.75,3724.28084,N,00640.30522,W,1,29,0.5,34.27,M,47.20,M,0,0*41
```

My thoughts are:
- Maybe should I update the firmware version of the MTi-680 DK? The MTi node shows a warning saying that the firmware version is old. In that case, I don't understand why with the MT Manager I can reach the fix status.
- Maybe the mti node is nos subscribing propperly to the /rtcm topic
- Maybe the mti node is not sending the corrections to the GNSS RTK daughter card.

I would appreciate if you could help me with this. I you require anything else, don't hesitate to ask. Thanks in advance.
